name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.0'

      - name: Install Make
        run: sudo apt-get install make

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
